### ISSUE TITLE
Important: Errors

### ISSUE THREAD

**Issue by blerude** [drum-IT/expresso#2]
https://github.com/drum-IT/expresso/blob/master/api/employees.js#L50-L86

While I understand your method of checking for employee validity up front and then just executing the appropriate route if those tests are passed, it is dangerous to not deal with potential errors resulting from any of the db calls here. You should add clauses to take care of that!

**Comment by drum-IT** [comment]
This is a good point. I'll add some error checking conditions.

**Comment by drum-IT** [comment]
Added error checking to all database queries where applicable.
