### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [drum-IT/expresso#4]
Grade: Meets Expectations

Great job on this project! Your code is easy to read and you've tackled every assigned route appropriately. You seem to have a great understanding of how to read from and write to the database using SQL, and your comments are very helpful. You approached the project in a very different way than I have previously seen by writing .use routes that check for employee/menu/timesheet validity regardless of what the route is (most people run that check within each function). I understand this approach and I like that you don't waste time entering the actual action route if there is an error up front, and I applaud your thought process.

The issue with that approach is that you have a false sense of security that no errors can occur within the get/post/etc. routes because you've in theory screened them up front. That's a dangerous assumption, so I encourage you to add clauses that handle the errors that those functions can produce. Otherwise, your code can break. Think about that moving forward, and again, great job here!

**Comment by drum-IT** [comment]
Thanks for the review and feedback!
